"""Deterministic index build: same corpus in, byte-identical files out."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from .corpus import Corpus



def _corpus_hash(corpus: Corpus, layers: set[str]) -> str:
    h = hashlib.sha256()
    files = [layer.domains_file for layer in corpus.layers if layer.name in layers and layer.domains_file.is_file()]
    files += sorted(r.path for r in corpus.rfcs.values() if r.layer in layers)
    for path in files:
        h.update(corpus.rel(path).encode())
        h.update(b"\0")
        h.update(path.read_bytes())
    return h.hexdigest()[:16]


def build_index(corpus: Corpus, layers: set[str] | None = None) -> dict:
    """Index of the given layers (default: local only, which is what a workspace commits).

    The committed index never embeds the parent corpus, so `build --check` in an app repo
    only depends on its own files; the parent is recorded by name and pinned ref.
    """
    layers = layers or {"local"}
    rfc_list = sorted((r for r in corpus.rfcs.values() if r.layer in layers), key=lambda r: r.id)
    used_domains = {r.domain for r in rfc_list}
    domains = [
        {
            "id": d.id, "title": d.title, "description": d.description, "owner": d.owner,
            "applies_when": d.applies_when, "not_applies_when": d.not_applies_when, "layer": d.layer,
            "rfcs": sorted(r.id for r in rfc_list if r.domain == d.id),
        }
        for d in sorted(corpus.domains.values(), key=lambda d: d.id)
        if d.layer in layers or d.id in used_domains
    ]
    rfcs, statements = [], []
    for rfc in rfc_list:
        rfcs.append({
            "id": rfc.id, "title": rfc.title, "status": rfc.status, "domain": rfc.domain, "layer": rfc.layer,
            "artifacts": rfc.artifacts, "languages": rfc.languages, "owner": rfc.owner,
            "review_by": rfc.review_by, "summary": rfc.summary,
            "applies_when": rfc.applies_when, "not_applies_when": rfc.not_applies_when,
            "supersedes": rfc.supersedes, "superseded_by": rfc.superseded_by, "retired": rfc.retired,
            "path": corpus.rel(rfc.path),
            "statements": [s.id for s in rfc.statements],
        })
        for st in rfc.statements:
            statements.append({
                "id": st.id, "rfc": rfc.id, "domain": rfc.domain, "status": rfc.status, "layer": rfc.layer,
                "title": st.title, "text": st.text, "level": st.level,
                "blocking": rfc.statement_blocking(st), "enforcement": st.enforcement,
                "applies_when": st.applies_when or rfc.applies_when,
                "not_applies_when": st.not_applies_when or rfc.not_applies_when,
                "artifacts": st.artifacts or rfc.artifacts, "languages": rfc.languages,
                "source": corpus.source(rfc, st.line),
                # only when present: entries of code/spec statements stay byte-identical
                **({"tools": st.tools} if st.tools else {}),
                **({"violated_when": st.violated_when} if st.violated_when else {}),
                **({"pattern": st.pattern} if st.pattern else {}),
            })
    parents = [
        {"name": layer.name, "repo": layer.parent.repo, "ref": layer.parent.ref, "prefix": layer.prefix}
        for layer in corpus.layers if not layer.local and layer.parent and layer.name not in layers
    ]
    return {
        "schema": 2,
        "corpus_hash": _corpus_hash(corpus, layers),
        "extends": parents,
        "counts": {"domains": len(domains), "rfcs": len(rfcs), "statements": len(statements)},
        "domains": domains,
        "rfcs": rfcs,
        "statements": statements,
    }


def render_catalog(index: dict) -> str:
    """Compact Markdown map for agents: domain -> RFC -> one line per statement."""
    by_rfc = {}
    for st in index["statements"]:
        by_rfc.setdefault(st["rfc"], []).append(st)
    rfcs = {r["id"]: r for r in index["rfcs"]}
    out = [
        "# jrfc catalog",
        "",
        "Generated by `jrfc build`. Do not edit. One line per statement:",
        "`ID [LEVEL, status, enforcement] title`. Open a statement with `jrfc show <ID>`.",
        "",
    ]
    for d in index["domains"]:
        if not d["rfcs"]:
            continue
        out.append(f"## {d['id']} — {d['title']}")
        out.append("")
        out.append(d["description"])
        out.append("")
        for rid in d["rfcs"]:
            r = rfcs[rid]
            layer = "" if r.get("layer", "local") == "local" else f" [{r['layer']}]"
            out.append(f"### {rid} {r['title']} ({r['status']}){layer} — `{r['path']}`")
            for st in by_rfc.get(rid, []):
                flag = "blocking" if st["blocking"] else st["status"]
                out.append(f"- `{st['id']}` [{st['level']}, {flag}, {st['enforcement']}] {st['title']}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def index_files(index: dict) -> dict[str, str]:
    return {
        "index.json": json.dumps(index, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        "catalog.md": render_catalog(index),
    }


def write_index(index: dict, out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in index_files(index).items():
        path = out_dir / name
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def check_index(index: dict, out_dir: Path) -> list[str]:
    """Return the names of index files that are missing or stale."""
    stale = []
    for name, content in index_files(index).items():
        path = out_dir / name
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(name)
    return stale
